# Generated by Django 5.2.1 on 2025-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestManagementSystemtApp', '0002_user_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
