# Generated by Django 5.2.1 on 2025-08-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestManagementSystemtApp', '0003_alter_user_options_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tokens', to='GuestManagementSystemtApp.customer'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tokens', to='GuestManagementSystemtApp.user'),
        ),
    ]
