# Generated by Django 5.2.1 on 2025-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestManagementSystemtApp', '0004_usertoken_customer_alter_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
    ]
