# Generated by Django 5.2.1 on 2025-08-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestManagementSystemtApp', '0006_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
