# Generated by Django 5.2.1 on 2025-08-11 16:34

import GuestManagementSystemtApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestManagementSystemtApp', '0007_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=GuestManagementSystemtApp.models.product_image_upload_path),
        ),
    ]
